### ISSUE TITLE
Emscripten `ClearRenderTarget()` issue

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#441] opened 2023-10-16 10:51 UTC
It seems this API accepts float RGBA, while the RTV could be in integral format... 
WebGL complains about calling the float version API on integral texture backed render target.
Not sure what's the "correct" way to fix this...

**Comment by crlf0710** [comment] 2023-10-16 10:52
seems duplicate of #287, sorry.

**Comment by TheMostDiligent** [comment] 2023-10-21 02:14
Duplicate of #287

**Closed** 2023-10-21 02:16 UTC
Labels: duplicate
