### ISSUE TITLE
Imgui shader breakage on iOS / OpenGL

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentCore#157] opened 2020-08-26 15:15 UTC
It seems Imgui might have gotten broken on your end for iOS / OpenGL platform.

Here is the excerpt from the log file:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#version 300 es
#extension GL_EXT_separate_shader_objects : enable
#ifndef GL_ES
# define GL_ES 1
#endif
#define PLATFORM_IOS 1
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp sampler3D;
precision highp samplerCube;
precision highp samplerCubeShadow;
precision highp sampler2DShadow;
precision highp sampler2DArray;
precision highp sampler2DArrayShadow;
precision highp isampler2D;
precision highp isampler3D;
precision highp isamplerCube;
precision highp isampler2DArray;
precision highp usampler2D;
precision highp usampler3D;
precision highp usamplerCube;
precision highp usampler2DArray;
layout(std140) uniform;
#define FRAGMENT_SHADER 1
#define PIXEL_SHADER 1
layout(binding = 0) uniform sampler2D Texture;
layout(location = 0) in vec4 vsout_col;
layout(location = 1) in vec2 vsout_uv;
layout(location = 0) out vec4 psout_col;

void main()
{
 psout_col = vsout_col * texture(Texture, vsout_uv);
}
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Diligent Engine: ERROR in ShaderGLImpl() (ShaderGLImpl.cpp, 127): Failed to compile shader file 'Imgui PS'
InfoLog:
ERROR: 0:28: Unknown identifier 'binding' in layout
ERROR: 0:37: Use of undeclared identifier 'Texture'Diligent Engine: ERROR in CreateDeviceObject() (RenderDeviceBase.hpp, 507): Failed to create shader object 'Imgui PS'

```

**Comment by TheMostDiligent** [comment] 2020-08-26 16:59
Duplicate of this one: https://github.com/DiligentGraphics/DiligentSamples/issues/26?
You shader code is out-of-date.

**Closed** 2020-08-26 18:18 UTC
Labels: duplicate
