### ISSUE TITLE
Two small linking issues with Diligent-Imgui.lib

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentCore#331] opened 2022-01-05 14:14 UTC
I noticed this when compiling Diligent from the command line on Windows:

`  Generating Code...
  Diligent-Imgui.lib(imgui.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library `

Note that I'm not sure if LIBCMT error is related to Diligent or some other lib, as command line error / warning logging is very sparse.

The LIBCMT issue can be rather tricky if various parts / libs of the project are using memory allocators from different base library variants, then if one lib allocates memory with one memory allocator and another lib frees it with a different memory allocator, it can lead to nasty & very hard to figure out heap related crashes.

**Comment by TheMostDiligent** [comment] 2022-01-07 04:38
Can you provide more information about your build setup:
- Which version of Visual Studio or build tools are you using?
- Which configuration are you building (settings for Debug and Release are quite different)
- Is this the fresh build?

Here is the link to the [latest Windows CI build](https://github.com/DiligentGraphics/DiligentEngine/actions/runs/1656731529) which ran clean in all 6 configurations.
Here is additional [Appveyor build](https://ci.appveyor.com/project/DiligentGraphics/diligentengine) that also ran without warnings.

Do you get this warning if you try to download and build the engine with your tools?

**Comment by TheMostDiligent** [comment] 2022-04-12 20:13
Closing this for now. Feel free to reopen if the issue is still relevant.

**Closed by TheMostDiligent** 2022-04-12 20:13 UTC
Labels: not reproducible
